```{r}
library(tidyverse)
library(ggthemes)
library(RColorBrewer)
```

```{r}
dat = read.csv("bixi1.csv")

```

```{r member}
donnees_summary <- dat %>%
  group_by(mem) %>%
  summarise(percentage = n() / nrow(dat) * 100)
# Création variable pour afficher en %

# Création du graphique à barres
ggplot(data = donnees_summary, aes(x = factor(mem), y = percentage, fill = factor(mem))) +
  geom_bar(stat = "identity") +
  guides(fill=guide_legend(title = "Membre"))+
  ggtitle("Pourcentage de membre et de non membre BIXI")+
  xlab("")+
  ylab("Pourcentage")+
  theme_minimal()
```

Graphique voyage par jour (découper par membre)
```{r}

dat$wday <- factor(dat$wday,
                   levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

label <- c(`1` = "Membre", `0` = "Non membre")

dat %>% 
ggplot(aes(x=wday, y=avg,
           fill = wday)) +
  geom_bar(stat = "identity") +
  theme_minimal()+
  scale_fill_brewer(palette = "Blues")+
  facet_wrap(~ mem,labeller=labeller(mem=label))+
  theme(legend.position="none")+
  labs(title = "Durée moyenne des déplacement \npar jours selon les membres et les non membres")+
  xlab("")+
  ylab("Durée moyenne (en minutes) des déplacement")
        
```

Même chose par mois
```{r}
ggplot(dat, aes(mm, avg)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  facet_wrap(~ mem)
```

Temp
```{r}
dat_temp <- dat %>%
  select(mem, avg, temp) %>% 
  group_by(temp, mem) %>%
  summarise(avg = mean(avg))

ggplot(dat_temp, aes(temp, avg)) +
  geom_line(stat = "identity") +
  theme_minimal() +
  facet_wrap(~ mem)
```

Rain
```{r}
dat_rain <- dat %>%
  select(mem, avg, rain) %>% 
  group_by(rain, mem) %>%
  summarise(avg = mean(avg))

ggplot(dat_rain, aes(rain, avg)) +
  geom_line(stat = "identity") +
  theme_minimal() +
  facet_wrap(~ mem)
```

Temps moyen selon membre
```{r}
dat_mem <- dat %>%
  select(mem, avg) %>% 
  group_by(mem) %>%
  summarise(avg = mean(avg))

print(dat_mem)
```

essaie de graph
```{r}
dat %>%  ggplot(aes(avg,temp))+
  geom_point()+
  theme_minimal()

dat %>% ggplot(aes(dur))+
  geom_density()
  


```
